apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
  spec:
    containers:
      - name: nexus
        image: customimage:v1
        ports:
          - containerPort: 8081
        volumeMounts:
          - name: nexus-data
            mountPath: /nexus-data
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
    volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-pvc
